name: 03 - Workflow Runners

on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS -01
              run: |
                echo "This job is running on a ubuntu runner."
                echo "Runner OS: $RUNNER_OS"


